#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════════
# run_node_mac.sh — macOS ControlPlane / Inference Hub / Storage Peer Launcher
# ═══════════════════════════════════════════════════════════════════════════════
#
# One-command startup for the macOS ControlPlane.
#   - Reads network state from .eo_network (generated by setup_env.sh)
#   - Builds the Rust node if needed, configures firewall, binds to LAN IP
#   - Waits for mDNS + libp2p to be ready, then prints the bootstrap multiaddr
#     you copy to Linux nodes
#   - Launches the eo-agent REPL for natural-language interaction
#
# Usage:
#   ./scripts/run_node_mac.sh                     # Full stack (node + agent)
#   ./scripts/run_node_mac.sh --node-only         # Node only, agent in another terminal
#   ./scripts/run_node_mac.sh --agent-only        # Agent only, connect to existing node
#   ./scripts/run_node_mac.sh --mock              # Demo mode (no Rust node, mock responses)
#
# Environment variables:
#   DEEPSEEK_API_KEY  — LLM API key (also reads OPENAI_API_KEY / ANTHROPIC_API_KEY)
#   EO_LLM_MODEL      — Model name (default: gpt-4o)
#   EO_LLM_BASE_URL   — Custom API base URL (for DeepSeek / Ollama / local models)
#   EO_HOME           — Storage root (default: ~/.eo_storage)
#   EO_IPC_SOCKET     — UDS path (default: /tmp/eo_control.sock)
#   RUST_LOG          — Tracing level (default: info)

set -euo pipefail

# ── Colours ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; CYAN='\033[0;36m'; NC='\033[0m'
info()  { echo -e "${BLUE}[INFO]${NC}  $*"; }
ok()    { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*"; }

# ── Paths ────────────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
LOG_DIR="$REPO_DIR/logs"
NETWORK_STATE="$REPO_DIR/.eo_network"
BOOTSTRAP_FILE="$REPO_DIR/.eo_bootstrap"
mkdir -p "$LOG_DIR"

export EO_HOME="${EO_HOME:-$HOME/.eo_storage}"
export EO_IPC_SOCKET="${EO_IPC_SOCKET:-/tmp/eo_control.sock}"
export RUST_LOG="${RUST_LOG:-info}"
export EO_LLM_MODEL="${EO_LLM_MODEL:-gpt-4o}"
CONFIG_FILE="$REPO_DIR/configs/mac-node.yaml"
STORE_DIR="$EO_HOME"
VENV_DIR="$REPO_DIR/eo-agent/.venv"
TS=$(date +%Y%m%d_%H%M%S)
NODE_LOG="$LOG_DIR/node_mac_$TS.log"
AGENT_LOG="$LOG_DIR/agent_mac_$TS.log"

# ── Parse flags ──────────────────────────────────────────────────────────────
AGENT_ONLY=false; NODE_ONLY=false; MOCK_MODE=false
for arg in "$@"; do
    case "$arg" in
        --agent-only) AGENT_ONLY=true ;;
        --node-only)  NODE_ONLY=true ;;
        --mock)       MOCK_MODE=true ;;
        *)            echo "Unknown: $arg" >&2; exit 2 ;;
    esac
done
$AGENT_ONLY && $NODE_ONLY && { echo "ERROR: --agent-only and --node-only are mutually exclusive" >&2; exit 2; }

# ── Pre-flight: check setup ──────────────────────────────────────────────────
preflight() {
    info "Pre-flight checks..."

    if [ ! -f "$NETWORK_STATE" ]; then
        warn ".eo_network not found — running setup_env.sh --network-only first..."
        "$SCRIPT_DIR/setup_env.sh" --network-only
    fi

    # Source network state
    PRIMARY_IP=$(grep "PRIMARY_IP=" "$NETWORK_STATE" 2>/dev/null | cut -d= -f2 || echo "")
    MDNS_OK=$(grep "MDNS_WORKING=" "$NETWORK_STATE" 2>/dev/null | cut -d= -f2 || echo "unknown")
    FIREWALL_ON=$(grep "FIREWALL_ON=" "$NETWORK_STATE" 2>/dev/null | cut -d= -f2 || echo "false")

    if [ -z "$PRIMARY_IP" ]; then
        warn "No LAN IP recorded — running network diagnostic..."
        "$SCRIPT_DIR/setup_env.sh" --network-only
        PRIMARY_IP=$(grep "PRIMARY_IP=" "$NETWORK_STATE" | cut -d= -f2)
    fi

    ok "LAN IP: $PRIMARY_IP  |  mDNS: $MDNS_OK  |  Firewall: $FIREWALL_ON"

    if [ "$MDNS_OK" = "false" ]; then
        warn "mDNS was NOT detected working. Peers may not auto-discover this node."
        warn "You'll need to manually share the bootstrap address (printed below) with Linux nodes."
    fi

    # Check storage exists
    if [ ! -d "$EO_HOME/objects" ]; then
        warn "Storage directories not found — running setup_env.sh..."
        "$SCRIPT_DIR/setup_env.sh"
    fi
}

# ── LLM Key check ────────────────────────────────────────────────────────────
check_llm_key() {
    # Merge common key aliases
    if [ -z "${DEEPSEEK_API_KEY:-}" ]; then
        [ -n "${OPENAI_API_KEY:-}" ]    && export DEEPSEEK_API_KEY="$OPENAI_API_KEY"
        [ -n "${ANTHROPIC_API_KEY:-}" ] && export DEEPSEEK_API_KEY="$ANTHROPIC_API_KEY"
        [ -n "${DEEPSEEK_API_KEY:-}" ]  && info "Using API key from existing env var"
    fi

    if [ -z "${DEEPSEEK_API_KEY:-}" ] && [ "$MOCK_MODE" = false ]; then
        echo ""
        echo -e "  ${YELLOW}┌─────────────────────────────────────────────────────────┐${NC}"
        echo -e "  ${YELLOW}│  No DEEPSEEK_API_KEY / OPENAI_API_KEY found.              │${NC}"
        echo -e "  ${YELLOW}│  The agent will run in MOCK mode (deterministic responses). │${NC}"
        echo -e "  ${YELLOW}│                                                         │${NC}"
        echo -e "  ${YELLOW}│  Set one of:                                            │${NC}"
        echo -e "  ${YELLOW}│    export DEEPSEEK_API_KEY=\"sk-...\"                     │${NC}"
        echo -e "  ${YELLOW}│    export OPENAI_API_KEY=\"sk-...\"                       │${NC}"
        echo -e "  ${YELLOW}│    export ANTHROPIC_API_KEY=\"sk-ant-...\"                │${NC}"
        echo -e "  ${YELLOW}│                                                         │${NC}"
        echo -e "  ${YELLOW}│  For custom endpoints (DeepSeek/Ollama/local):            │${NC}"
        echo -e "  ${YELLOW}│    export EO_LLM_BASE_URL=\"https://api.deepseek.com/v1\"  │${NC}"
        echo -e "  ${YELLOW}│    export EO_LLM_MODEL=\"deepseek-chat\"                   │${NC}"
        echo -e "  ${YELLOW}└─────────────────────────────────────────────────────────┘${NC}"
        echo ""
        export EO_MOCK_MODE=true
    fi

    # Show what's configured
    if [ -n "${DEEPSEEK_API_KEY:-}" ]; then
        ok "LLM Key: [set] ($(echo "$DEEPSEEK_API_KEY" | wc -c | xargs) chars)"
    fi
    [ -n "${EO_LLM_BASE_URL:-}" ] && ok "LLM Base URL: $EO_LLM_BASE_URL"
    ok "LLM Model: $EO_LLM_MODEL"
}

# ── Firewall config for node binary ───────────────────────────────────────────
configure_firewall() {
    if [ "$FIREWALL_ON" != "true" ] || [ "$MOCK_MODE" = true ]; then return; fi

    local node_bin="$REPO_DIR/target/release/node"
    if [ ! -f "$node_bin" ]; then return; fi

    info "Configuring macOS firewall for node binary..."
    sudo -n true 2>/dev/null || { warn "Sudo needed for firewall — skipping (re-run with sudo available)"; return; }
    sudo /usr/libexec/ApplicationFirewall/socketfilterfw --add "$node_bin" 2>/dev/null || true
    sudo /usr/libexec/ApplicationFirewall/socketfilterfw --unblockapp "$node_bin" 2>/dev/null || true
    ok "Firewall: node binary allowed"
}

# ── Build if needed ──────────────────────────────────────────────────────────
build_node() {
    if [ "$MOCK_MODE" = true ] || [ "$AGENT_ONLY" = true ]; then return; fi
    if [ -f "$REPO_DIR/target/release/node" ]; then
        ok "Node binary found — skipping build"
        return
    fi
    info "Building Rust node (release mode — one-time, ~2-5 min)..."
    cd "$REPO_DIR"
    cargo build --release -p node
    ok "Build complete"
}

# ── Launch Rust node ─────────────────────────────────────────────────────────
launch_node() {
    echo ""
    echo -e "${CYAN}══════════════════════════════════════════════════════════════${NC}"
    echo -e "${CYAN}  Rust Node — macOS ControlPlane${NC}"
    echo -e "${CYAN}══════════════════════════════════════════════════════════════${NC}"
    echo ""
    echo "  Config:       $CONFIG_FILE"
    echo "  Store:        $STORE_DIR"
    echo "  IPC Socket:   $EO_IPC_SOCKET"
    echo "  Log:          $NODE_LOG"
    echo ""

    # Clean stale socket
    [ -S "$EO_IPC_SOCKET" ] && rm -f "$EO_IPC_SOCKET"

    cd "$REPO_DIR"
    "$REPO_DIR/target/release/node" \
        --config "$CONFIG_FILE" \
        --store-dir "$STORE_DIR" \
        --ipc-socket "$EO_IPC_SOCKET" \
        --log-level "$RUST_LOG" \
        > "$NODE_LOG" 2>&1 &

    NODE_PID=$!
    echo "  PID: $NODE_PID"
    echo "$NODE_PID" > /tmp/eo_node_mac.pid

    # Wait for IPC socket (max 15s)
    echo -n "  Waiting for IPC socket..."
    for i in $(seq 1 15); do
        if [ -S "$EO_IPC_SOCKET" ]; then
            echo " ready (${i}s)"
            chmod 660 "$EO_IPC_SOCKET" 2>/dev/null || chmod 666 "$EO_IPC_SOCKET" 2>/dev/null || true
            ok "IPC socket: $EO_IPC_SOCKET (rw for user+group)"
            break
        fi
        sleep 1; echo -n "."
    done
    if [ ! -S "$EO_IPC_SOCKET" ]; then
        error "IPC socket did not appear. Check: tail -50 $NODE_LOG"
        return 1
    fi

    # Wait for libp2p to bind & mDNS announce (~5-10s)
    echo -n "  Waiting for libp2p + mDNS announcement..."
    for i in $(seq 1 10); do
        if grep -q "Listening on" "$NODE_LOG" 2>/dev/null; then
            echo " ready (${i}s)"
            break
        fi
        sleep 1; echo -n "."
    done

    # Extract the multiaddr + PeerId for sharing with Linux peers
    LISTEN_LINE=$(grep "Listening on" "$NODE_LOG" 2>/dev/null | tail -1 || echo "")
    if [ -n "$LISTEN_LINE" ]; then
        # "Listening on /ip4/192.168.1.42/tcp/42069/p2p/12D3KooWAbCdEfGh..."
        FULL_ADDR=$(echo "$LISTEN_LINE" | awk '{print $NF}')
        PEER_ID=$(echo "$FULL_ADDR" | awk -F'/p2p/' '{print $NF}')

        echo ""
        echo -e "  ${GREEN}┌──────────────────────────────────────────────────────────────────────────┐${NC}"
        echo -e "  ${GREEN}│  Bootstrap Multiaddr (copy this for Linux nodes):                        │${NC}"
        echo -e "  ${GREEN}│                                                                          │${NC}"
        echo -e "  ${GREEN}│  $FULL_ADDR${NC}"
        echo -e "  ${GREEN}│                                                                          │${NC}"
        echo -e "  ${GREEN}│  Paste into configs/linux-node.yaml:                                     │${NC}"
        echo -e "  ${GREEN}│    bootstrap_peers:                                                      │${NC}"
        echo -e "  ${GREEN}│      - \"$FULL_ADDR\"                                                │${NC}"
        echo -e "  ${GREEN}└──────────────────────────────────────────────────────────────────────────┘${NC}"
        echo ""

        # Persist for other scripts
        cat > "$BOOTSTRAP_FILE" <<EOF
# Edge-Cloud Orchestrator — ControlPlane Bootstrap Info
# Generated: $(date)
EOF_IP=$PRIMARY_IP
EOF_PORT=$(echo "$FULL_ADDR" | awk -F'/' '{for(i=1;i<=NF;i++) if($i=="tcp") print $(i+1)}')
PEER_ID=$PEER_ID
FULL_ADDR=$FULL_ADDR
EOF
        echo "EOF_IP=$PRIMARY_IP" >> "$BOOTSTRAP_FILE"
        echo "EOF_PORT=${EOF_PORT:-42069}" >> "$BOOTSTRAP_FILE"
        echo "PEER_ID=$PEER_ID" >> "$BOOTSTRAP_FILE"
        echo "FULL_ADDR=$FULL_ADDR" >> "$BOOTSTRAP_FILE"
    else
        warn "Could not extract libp2p address from log — check: grep 'Listening on' $NODE_LOG"
    fi
}

# ── Launch eo-agent REPL ─────────────────────────────────────────────────────
launch_agent() {
    echo ""
    echo -e "${CYAN}══════════════════════════════════════════════════════════════${NC}"
    echo -e "${CYAN}  eo-agent REPL${NC}"
    echo -e "${CYAN}══════════════════════════════════════════════════════════════${NC}"
    echo ""

    if [ ! -f "$VENV_DIR/bin/python" ]; then
        error "Virtualenv not found at $VENV_DIR. Run: ./scripts/setup_env.sh"
        exit 1
    fi

    if [ "$MOCK_MODE" = true ]; then
        export EO_MOCK_MODE=true
        echo "  Mode: MOCK (no Rust node, deterministic responses)"
    else
        export EO_MOCK_MODE=false
        echo "  Mode: PRODUCTION  |  Socket: $EO_IPC_SOCKET"
    fi

    echo "  LLM:   ${EO_LLM_MODEL}  |  Key: ${DEEPSEEK_API_KEY:+[set]}${DEEPSEEK_API_KEY:-[mock]}"
    [ -n "${EO_LLM_BASE_URL:-}" ] && echo "  URL:   $EO_LLM_BASE_URL"
    echo "  Log:   $AGENT_LOG"
    echo ""

    cd "$REPO_DIR"
    source "$VENV_DIR/bin/activate"
    "$VENV_DIR/bin/eo-agent" --interactive --socket "$EO_IPC_SOCKET" 2>&1 | tee "$AGENT_LOG"
}

# ── Cleanup ──────────────────────────────────────────────────────────────────
cleanup_node() {
    if [ -f /tmp/eo_node_mac.pid ]; then
        NPID=$(cat /tmp/eo_node_mac.pid)
        if kill -0 "$NPID" 2>/dev/null; then
            echo ""; info "Stopping node (PID $NPID)..."
            kill "$NPID" 2>/dev/null || true
            sleep 1; kill -9 "$NPID" 2>/dev/null || true
            ok "Node stopped"
        fi
        rm -f /tmp/eo_node_mac.pid
    fi
    [ -S "$EO_IPC_SOCKET" ] && rm -f "$EO_IPC_SOCKET"
    echo "Goodbye."
}
trap cleanup_node EXIT INT TERM

# ── Main ─────────────────────────────────────────────────────────────────────
echo ""
echo -e "${CYAN}  ╔══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}  ║   Edge-Cloud Orchestrator — macOS ControlPlane               ║${NC}"
echo -e "${CYAN}  ║   $(uname -s) $(uname -m) — $(date)                 ║${NC}"
echo -e "${CYAN}  ╚══════════════════════════════════════════════════════════════╝${NC}"

preflight
check_llm_key
build_node
configure_firewall

if $AGENT_ONLY; then
    launch_agent
elif $NODE_ONLY; then
    launch_node
    echo ""
    echo "Node running. Press Ctrl+C to stop."
    echo "Monitor:  tail -f $NODE_LOG"
    while true; do sleep 1; done
else
    launch_node
    launch_agent
fi
