#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════════
# run_node_linux.sh — Linux Execution Node / Storage Peer Launcher
# ═══════════════════════════════════════════════════════════════════════════════
#
# One-command startup for any Linux execution node (bare-metal, VMware, cloud VM).
#   - Reads network state from .eo_network (generated by setup_env.sh)
#   - Reads bootstrap multiaddr from .eo_bootstrap (copy from Mac after it starts)
#   - Auto-detects VMware + bridged mode, installs avahi-daemon, configures UFW
#   - Tries mDNS discovery first; falls back to explicit bootstrap peer
#   - Profiles system resources and starts the Rust node
#
# Usage:
#   ./scripts/run_node_linux.sh
#   ./scripts/run_node_linux.sh /ip4/192.168.1.42/tcp/42069/p2p/12D3KooW...
#
# Environment variables:
#   EO_HOME       — Storage root (default: ~/.eo_storage)
#   EO_IPC_SOCKET — UDS path (default: /tmp/eo_control.sock)
#   RUST_LOG      — Tracing level (default: info)

set -euo pipefail

# ── Colours ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; CYAN='\033[0;36m'; NC='\033[0m'
info()  { echo -e "${BLUE}[INFO]${NC}  $*"; }
ok()    { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*"; }

# ── Paths ────────────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
LOG_DIR="$REPO_DIR/logs"
NETWORK_STATE="$REPO_DIR/.eo_network"
BOOTSTRAP_FILE="$REPO_DIR/.eo_bootstrap"
mkdir -p "$LOG_DIR"

export EO_HOME="${EO_HOME:-$HOME/.eo_storage}"
export EO_IPC_SOCKET="${EO_IPC_SOCKET:-/tmp/eo_control.sock}"
export RUST_LOG="${RUST_LOG:-info}"
CONFIG_FILE="$REPO_DIR/configs/linux-node.yaml"
STORE_DIR="$EO_HOME"
TS=$(date +%Y%m%d_%H%M%S)
NODE_LOG="$LOG_DIR/node_linux_$TS.log"

# ── Pre-flight ───────────────────────────────────────────────────────────────
preflight() {
    info "Pre-flight checks..."

    # Run network diagnostic if not done yet
    if [ ! -f "$NETWORK_STATE" ]; then
        warn ".eo_network not found — running setup_env.sh --network-only..."
        "$SCRIPT_DIR/setup_env.sh" --network-only
    fi

    # Source network state
    PRIMARY_IP=$(grep "PRIMARY_IP=" "$NETWORK_STATE" 2>/dev/null | cut -d= -f2 || echo "")
    MDNS_OK=$(grep "MDNS_WORKING=" "$NETWORK_STATE" 2>/dev/null | cut -d= -f2 || echo "unknown")
    FIREWALL_ON=$(grep "FIREWALL_ON=" "$NETWORK_STATE" 2>/dev/null | cut -d= -f2 || echo "false")
    IS_VM=$(grep "IS_VM=" "$NETWORK_STATE" 2>/dev/null | cut -d= -f2 || echo "false")

    ok "LAN IP: ${PRIMARY_IP:-unknown}  |  mDNS: $MDNS_OK  |  VM: $IS_VM"

    if [ "$IS_VM" = "true" ]; then
        warn "Running in VMware VM — ensure Network Adapter is set to BRIDGED MODE."
        warn "  VMware → VM Settings → Network Adapter → Bridged: Connected directly to the physical network"
        warn "  Advanced → ✓ Replicate physical network connection state"
        echo ""
    fi

    # Ensure avahi-daemon
    if ! systemctl is-active --quiet avahi-daemon 2>/dev/null; then
        info "Installing avahi-daemon for mDNS discovery..."
        sudo -n true 2>/dev/null || { warn "Sudo needed for apt install — enter password:"; sudo -v; }
        sudo apt update -qq && sudo apt install avahi-daemon -y -qq
        sudo systemctl enable --now avahi-daemon
        ok "avahi-daemon installed & running"
    fi

    # Ensure UFW is configured
    if [ "$FIREWALL_ON" = "true" ]; then
        info "Configuring UFW..."
        sudo ufw allow 5353/udp comment 'eo-mDNS' 2>/dev/null || true
        sudo ufw allow 42000:43000/tcp comment 'eo-libp2p' 2>/dev/null || true
        ok "UFW: UDP 5353 + TCP 42000-43000"
    fi

    # Storage dirs
    if [ ! -d "$EO_HOME/objects" ]; then
        warn "Storage not set up — running setup_env.sh..."
        "$SCRIPT_DIR/setup_env.sh"
    fi
}

# ── Find the ControlPlane ────────────────────────────────────────────────────
discover_control_plane() {
    local bootstrap_addr="${1:-}"

    # Priority 1: explicit bootstrap multiaddr on command line
    if [ -n "$bootstrap_addr" ] && echo "$bootstrap_addr" | grep -q "/p2p/"; then
        ok "Using bootstrap peer: $bootstrap_addr"
        echo "$bootstrap_addr"
        return
    fi

    # Priority 2: .eo_bootstrap file (copied from Mac)
    if [ -f "$BOOTSTRAP_FILE" ]; then
        FULL_ADDR=$(grep "FULL_ADDR=" "$BOOTSTRAP_FILE" 2>/dev/null | cut -d= -f2- || echo "")
        if [ -n "$FULL_ADDR" ]; then
            ok "Using bootstrap from .eo_bootstrap: $FULL_ADDR"
            info "  (copy this file from Mac: scp mac:edge-orchestrator/.eo_bootstrap .eo_bootstrap)"
            echo "$FULL_ADDR"
            return
        fi
    fi

    # Priority 3: try mDNS discovery — scan for the Mac node
    info "No bootstrap peer specified — trying mDNS discovery (5s scan)..."
    if have avahi-browse; then
        MDNS_RESULTS=$(timeout 6 avahi-browse -a -t -k 2>/dev/null || echo "")
        if [ -n "$MDNS_RESULTS" ]; then
            ok "mDNS scan found services — will attempt automatic peer discovery"
            ok "  (Rust node will use mDNS to find the ControlPlane)"
            echo ""  # empty = rely on mDNS
            return
        fi
    fi

    # Priority 4: couldn't find anything — instruct user
    echo ""
    echo -e "  ${YELLOW}┌──────────────────────────────────────────────────────────────────────┐${NC}"
    echo -e "  ${YELLOW}│  ⚠ COULD NOT FIND THE CONTROLPLANE                                   │${NC}"
    echo -e "  ${YELLOW}│                                                                      │${NC}"
    echo -e "  ${YELLOW}│  mDNS scan returned nothing and no bootstrap peer was provided.       │${NC}"
    echo -e "  ${YELLOW}│                                                                      │${NC}"
    echo -e "  ${YELLOW}│  On the Mac (ControlPlane), run:                                     │${NC}"
    echo -e "  ${YELLOW}│    cat edge-orchestrator/.eo_bootstrap                               │${NC}"
    echo -e "  ${YELLOW}│                                                                      │${NC}"
    echo -e "  ${YELLOW}│  Copy the FULL_ADDR line and re-run:                                 │${NC}"
    echo -e "  ${YELLOW}│    ./scripts/run_node_linux.sh /ip4/X.X.X.X/tcp/XXXXX/p2p/12D3KooW...│${NC}"
    echo -e "  ${YELLOW}│                                                                      │${NC}"
    echo -e "  ${YELLOW}│  Or copy .eo_bootstrap from Mac to this machine:                      │${NC}"
    echo -e "  ${YELLOW}│    scp mac:edge-orchestrator/.eo_bootstrap .                          │${NC}"
    echo -e "  ${YELLOW}└──────────────────────────────────────────────────────────────────────┘${NC}"
    echo ""

    if [ "$MDNS_OK" = "false" ]; then
        error "mDNS was already detected as non-functional. You MUST provide a bootstrap peer."
        exit 1
    fi

    warn "Proceeding with mDNS-only mode — node will start but may not find peers."
    echo ""
}

# ── System profile ───────────────────────────────────────────────────────────
system_profile() {
    echo ""
    echo -e "${CYAN}══════════════════════════════════════════════════════════════${NC}"
    echo -e "${CYAN}  Linux Execution Node — System Profile${NC}"
    echo -e "${CYAN}══════════════════════════════════════════════════════════════${NC}"
    echo ""
    echo "  Hostname:     $(hostname)"
    echo "  Kernel:       $(uname -r)"
    echo "  Arch:         $(uname -m)"
    echo "  CPUs:         $(nproc) cores"
    echo "  Memory:       $(free -h | awk '/^Mem:/ {print $2}')"
    echo "  Disk:         $(df -h "$EO_HOME" 2>/dev/null | awk 'NR==2 {print $4 " available"}')"

    # Docker check
    if command -v docker >/dev/null 2>&1; then
        info "Docker:    $(docker --version 2>/dev/null | head -1)  → Container runtime AVAILABLE"
    else
        warn "Docker:    NOT INSTALLED  → Container runtime UNAVAILABLE"
        warn "  Install: curl -fsSL https://get.docker.com | sudo sh"
    fi

    # Wasmtime check (bundled via Cargo, no action needed)
    ok "Wasm runtime: bundled via Wasmtime (always available)"
}

# ── Build if needed ──────────────────────────────────────────────────────────
build_node() {
    if [ -f "$REPO_DIR/target/release/node" ]; then
        ok "Node binary found — skipping build"
        return
    fi
    info "Building Rust node (release mode — one-time, ~2-5 min)..."
    cd "$REPO_DIR"
    cargo build --release -p node
    ok "Build complete"
}

# ── Write bootstrap config ───────────────────────────────────────────────────
write_bootstrap_config() {
    local bootstrap_addr="$1"
    if [ -z "$bootstrap_addr" ]; then
        info "No bootstrap peer — node will use mDNS-only discovery"
        return
    fi

    # Write a temporary config override with the bootstrap peer
    # (We don't modify the original linux-node.yaml — use a temp copy)
    TMP_CONFIG="/tmp/eo_linux_config_$$.yaml"
    cp "$CONFIG_FILE" "$TMP_CONFIG"

    # Replace bootstrap_peers in the temp config
    python3 -c "
import yaml, sys
with open('$TMP_CONFIG') as f:
    cfg = yaml.safe_load(f)
cfg['bootstrap_peers'] = ['$bootstrap_addr']
with open('$TMP_CONFIG', 'w') as f:
    yaml.dump(cfg, f, default_flow_style=False)
" 2>/dev/null || {
        warn "Python YAML not available — editing config manually"
        sed -i "s|bootstrap_peers: \[\]|bootstrap_peers: [\"$bootstrap_addr\"]|" "$TMP_CONFIG"
    }

    CONFIG_FILE="$TMP_CONFIG"
    ok "Config prepared with bootstrap peer"
}

# ── Launch ───────────────────────────────────────────────────────────────────
launch_node() {
    echo ""
    echo -e "${CYAN}══════════════════════════════════════════════════════════════${NC}"
    echo -e "${CYAN}  Starting Rust Node (Linux — Execution + Storage)${NC}"
    echo -e "${CYAN}══════════════════════════════════════════════════════════════${NC}"
    echo ""
    echo "  Config:       $CONFIG_FILE"
    echo "  Store:        $STORE_DIR"
    echo "  IPC Socket:   $EO_IPC_SOCKET"
    echo "  Log:          $NODE_LOG"
    echo ""

    [ -S "$EO_IPC_SOCKET" ] && rm -f "$EO_IPC_SOCKET"

    cd "$REPO_DIR"
    echo "  Starting node (Ctrl+C to stop)..."
    echo ""

    cleanup() {
        echo ""; info "Shutting down Linux node..."
        [ -S "$EO_IPC_SOCKET" ] && rm -f "$EO_IPC_SOCKET"
        ok "Goodbye."
    }
    trap cleanup EXIT INT TERM

    exec "$REPO_DIR/target/release/node" \
        --config "$CONFIG_FILE" \
        --store-dir "$STORE_DIR" \
        --ipc-socket "$EO_IPC_SOCKET" \
        --log-level "$RUST_LOG" 2>&1 | tee "$NODE_LOG"
}

# ── Main ─────────────────────────────────────────────────────────────────────
BOOTSTRAP_ADDR="${1:-}"  # optional positional argument

echo ""
echo -e "${CYAN}  ╔══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}  ║   Edge-Cloud Orchestrator — Linux Execution Node             ║${NC}"
echo -e "${CYAN}  ║   $(uname -s) $(uname -m) — $(date)                 ║${NC}"
echo -e "${CYAN}  ╚══════════════════════════════════════════════════════════════╝${NC}"

preflight
system_profile

# If .eo_bootstrap exists and exists on this machine, use it
if [ -z "$BOOTSTRAP_ADDR" ] && [ -f "$BOOTSTRAP_FILE" ]; then
    BOOTSTRAP_ADDR=$(grep "FULL_ADDR=" "$BOOTSTRAP_FILE" 2>/dev/null | cut -d= -f2- || echo "")
    [ -n "$BOOTSTRAP_ADDR" ] && info "Found .eo_bootstrap from ControlPlane"
fi

BOOTSTRAP_ADDR=$(discover_control_plane "$BOOTSTRAP_ADDR")

build_node
if [ -n "$BOOTSTRAP_ADDR" ] && echo "$BOOTSTRAP_ADDR" | grep -q "/p2p/"; then
    write_bootstrap_config "$BOOTSTRAP_ADDR"
fi
launch_node
