"""Agent state definition for the LangGraph ReAct workflow.

All fields flow through the graph nodes. The ``messages`` field uses
LangGraph's ``add_messages`` reducer to automatically append new
messages to the conversation history.
"""

from typing import Annotated, Optional, TypedDict

from langgraph.graph.message import add_messages
from langchain_core.messages import BaseMessage


class AgentState(TypedDict, total=False):
    """Mutable state bag flowing through the ReAct graph.

    ``total=False`` means all keys are optional — each node only writes
    the fields it is responsible for. LangGraph merges partial updates.
    """

    # ── Conversation ──────────────────────────────────────────────
    messages: Annotated[list[BaseMessage], add_messages]
    """Conversation history. The add_messages reducer appends new entries."""

    # ── Planner output ────────────────────────────────────────────
    user_intent: str
    """Parsed user intention from the Planner node."""

    execution_plan: list[dict]
    """Structured plan: [{"step": 1, "action": "...", "target": "..."}, ...]."""

    # ── Coder output ──────────────────────────────────────────────
    generated_code: Optional[str]
    """Code generated by the Coder node."""

    code_language: Optional[str]
    """Language of the generated code: "wasm" | "python" | "posix"."""

    # ── Deployment (router) output ────────────────────────────────
    code_hash: Optional[str]
    """SHA-256 content hash returned by submit_to_cas_and_raft."""

    task_id: Optional[str]
    """UUID of the scheduled task."""

    # ── Evaluator output ──────────────────────────────────────────
    exit_code: Optional[int]
    """Exit code from the execution result (0 = success)."""

    stdout: Optional[str]
    """Decoded stdout from the sandbox execution."""

    stderr: Optional[str]
    """Decoded stderr from the sandbox execution (error feedback)."""

    execution_time_ms: Optional[int]
    """Wall-clock execution time in milliseconds."""

    # ── Self-correction tracking ──────────────────────────────────
    retry_count: int
    """Number of times the Coder→Deploy→Evaluate loop has iterated."""

    last_error: Optional[str]
    """Error feedback fed back to the Coder node on retry."""

    # ── Terminal ──────────────────────────────────────────────────
    final_answer: Optional[str]
    """Terminal output shown to the user when the workflow completes."""
